version: 2.8.0.{build}
os: Visual Studio 2017
configuration: Debug
platform: Any CPU

branches:
  only:
  - master

skip_tags: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: bY3HMQXJsuuHTqtDx878B8dh+vRw8Sr+ffu+i2ycNlnvN3NUsGXVCj/SUBlbsNdL

install:
- cmd: git submodule update --init --recursive
- cmd: dotnet restore MimeKit.sln

build:
  project: MimeKit.sln
  verbosity: minimal
  parallel: true

test_script:
- cmd: appveyor.bat
